# Site settings
title: Alpha Project
email: president@alphaproject.me
description: > # this means to ignore newlines until "baseurl:"
  Alpha Project is UBC organization in which members collectively work on creating an open-source software engineering project which is beneficial to the UBC community.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alphaproject.fn.lc" # the base hostname & protocol for your site
twitter_username: UBCAlphaProject
github_username:  UBCAlphaProject

# Build settings
markdown: kramdown
